/* 
    PSPPIRE --- A Graphical User Interface for PSPP
    Copyright (C) 2004, 2005  Free Software Foundation
    Written by John Darrington

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
    02110-1301, USA. */

/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */


#include <gtk/gtk.h>
#include <gtk/gtk.h>
#include <glade/glade.h>
#include "menu-actions.h"
#include "psppire-dict.h"
#include "psppire-var-store.h"
#include "psppire-data-store.h"

#include "helper.h"
#include "data-sheet.h"
#include "var-sheet.h"
#include "psppire-case-array.h"

GladeXML *xml;


PsppireDict *the_dictionary = 0;
PsppireCaseArray *the_cases = 0;


PsppireDataStore *data_store = 0;


int 
main(int argc, char *argv[]) 
{

  gtk_init(&argc, &argv);

  glade_init();

  the_dictionary = psppire_dict_new();

  /* Create the model for the var_sheet */
  PsppireVarStore *var_store = psppire_var_store_new(the_dictionary);

  /* Create the model for the data sheet */
  the_cases = psppire_case_array_new(100, 20);

  data_store = psppire_data_store_new(the_dictionary, the_cases);


  /* load the interface */
  xml = glade_xml_new("psppire.glade", NULL, NULL);

  if ( !xml ) 
    {
      g_print("Is psppire.glade in current directory?\n");
      return 1;
    }

  GtkWidget *data_editor = get_widget_assert(xml, "data_editor");
  gtk_window_set_icon_from_file(GTK_WINDOW(data_editor), "psppicon.png",0);

  /* connect the signals in the interface */
  glade_xml_signal_autoconnect(xml);

  GtkSheet *var_sheet  = GTK_SHEET(get_widget_assert(xml, "variable_sheet"));
  GtkSheet *data_sheet = GTK_SHEET(get_widget_assert(xml, "data_sheet"));

  gtk_sheet_set_model(var_sheet, G_SHEET_MODEL(var_store));
  
  gtk_sheet_set_model(data_sheet, G_SHEET_MODEL(data_store));


  gtk_init_add(callbacks_on_init, 0);

  /* start the event loop */
  gtk_main();
  return 0;
}

