@node Bugs
@chapter Bugs

@cindex bugs

Occasionally users encounter problems with @pspp{}.
When such problems arise we do our best to fix them, but our limited
resources mean that certain issues may remain for some time.
If you discover a bug, please first:
@itemize @bullet
@item Try an up to date version of @pspp{}; it may be that the problem 
 has recently been fixed.
@item If the problem persists in the up to date version; check to see
 if it has already been reported.
@item If the problem exists in a recent version and it has not already 
 been reported, please file a report.
@end itemize

To see a list of reported bugs, visit @pspp{}'s project webpage at
@uref{http://savannah.gnu.org/bugs/?group=pspp}
Alternatively, bug reports may be sent by email
to @email{bug-gnu-pspp@@gnu.org}.

In your bug report please include:
@itemize @bullet
@item The version of @pspp{} which you are using.
@item The operating system and type of computer on which it is running.
@item A sample of the syntax which causes the problem or, if it is a user
 interface problem, the sequence of steps required to reproduce it.
@item A description of what you think is wrong: What happened that you 
  didn't expect, and what did you expect to happen?
@end itemize

For known bugs in individual language features, see the documentation
for that feature.

