@node Bugs
@chapter Bugs

PSPP does have bugs.  We do our best to fix them, but our limited
resources mean that some may remain for a long time.  Our best
alternative is to make you aware of PSPP's known bugs.  To see a list,
visit PSPP's project webpage at
@uref{https://savannah.gnu.org/projects/pspp}.  You can also submit
your own bug report there: click on ``Bugs,'' then on ``Submit a
Bug,'' and fill out the form.  Alternatively, PSPP bug reports may be
sent by email to
@ifinfo
<bug-gnu-pspp@@gnu.org>.
@end ifinfo
@iftex
@code{<bug-gnu-pspp@@gnu.org>}.
@end iftex

For known bugs in individual language features, see the documentation
for that feature.

