@node Credits, Invocation, License, Top
@chapter Credits
@cindex credits
@cindex authors

@cindex Pfaff, Ben
Most of PSPP, as well as this manual,
was written by Ben Pfaff.  @xref{Contacting the Author}, for
instructions on contacting the author.

@cindex Covington, Michael A.
@cindex Van Zandt, James
@cindex @file{ftp.cdrom.com}
@cindex @file{/pub/algorithms/c/julcal10}
@cindex @file{julcal.c}
@cindex @file{julcal.h}
The PSPP source code incorporates @code{julcal10} originally
written by Michael A. Covington and translated into C by Jim Van Zandt.
The original package can be found in directory
@url{ftp://ftp.cdrom.com/pub/algorithms/c/julcal10}.  The entire
contents of that directory constitute the package.  The files actually
used in PSPP are @code{julcal.c} and @code{julcal.h}.
@setfilename ignored
