\input texinfo @c -*- texinfo -*-
@c %**start of header
@setfilename pspp.info
@settitle PSPP
@c For double-sided printing, uncomment:
@c @setchapternewpage odd
@c %**end of header

@include version.texi

@macro cmd{CMDNAME}
\CMDNAME\
@end macro

@iftex
@finalout
@end iftex

@dircategory Math
@direntry
* PSPP: (pspp).             Statistical analysis package.
@end direntry

@copying
This manual is for GNU PSPP version @value{VERSION},
software for statistical analysis.

Copyright @copyright{} 1997, 1998, 2004, 2005 Free Software Foundation, Inc.

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.1 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with the Front-Cover Texts being ``A GNU Manual,''
and with the Back-Cover Texts as in (a) below.  A copy of the
license is included in the section entitled ``GNU Free Documentation
License.''

(a) The FSF's Back-Cover Text is: ``You have freedom to copy and modify
this GNU Manual, like GNU software.  Copies published by the Free
Software Foundation raise funds for GNU development.''
@end quotation
@end copying

@titlepage
@title GNU PSPP
@subtitle A System for Statistical Analysis
@subtitle Edition @value{EDITION}, for PSPP version @value{VERSION}
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents


@ifnottex
@node Top
@top GNU PSPP

@insertcopying
@end ifnottex

@menu
* Introduction::                Description of the package.
* License::                     Your rights and obligations.

* Invocation::                  Starting and running PSPP.
* Language::                    Basics of the PSPP command language.
* Expressions::                 Numeric and string expression syntax.

* Data Input and Output::       Reading data from user files.
* System and Portable Files::   Dealing with system & portable files.
* Variable Attributes::         Adjusting and examining variables.
* Data Manipulation::           Simple operations on data.
* Data Selection::              Select certain cases for analysis.
* Conditionals and Looping::    Doing things many times or not at all.
* Statistics::                  Basic statistical procedures.
* Utilities::                   Other commands.

* Not Implemented::             What's not here yet
* Bugs::                        Known problems; submitting bug reports.

* Function Index::              Index of PSPP functions for expressions.
* Command Index::               Index of PSPP procedures.
* Concept Index::               Index of concepts.

* Configuration::               Configuring PSPP.

* Portable File Format::        Format of PSPP portable files.
* System File Format::          Format of PSPP system files.
* q2c Input Format::            Format of syntax accepted by q2c.

* GNU Free Documentation License:: License for copying this manual.
@end menu

@include introduction.texi
@include license.texi

@include invoking.texi
@include language.texi
@include expressions.texi
@include data-io.texi
@include files.texi
@include variables.texi
@include transformation.texi
@include data-selection.texi
@include flow-control.texi
@include statistics.texi
@include utilities.texi
@include not-implemented.texi
@include bugs.texi

@include function-index.texi
@include command-index.texi
@include concept-index.texi

@include configuring.texi

@include portable-file-format.texi
@include data-file-format.texi
@include q2c.texi

@include fdl.texi

@bye

@c Local Variables:
@c use (texinfo-multiple-files-update "pspp.texinfo")  in emacs to keep these files consistent
@c compile-command: "makeinfo pspp.texinfo"
@c End:
