\input texinfo @c -*- texinfo -*-
@c %**start of header
@setfilename pspp.info
@settitle PSPP
@c For double-sided printing, uncomment:
@c @setchapternewpage odd
@c %**end of header


@macro note{param1}
@quotation
@strong{Please note:} \param1\
@end quotation
@end macro

@include version.texi

@macro cmd{CMDNAME}
\CMDNAME\
@end macro

@ifset MISSING_CLICKSEQUENCE
@alias clicksequence = asis
@macro click {}
->
@end macro
@end ifset

@iftex
@finalout
@end iftex

@dircategory Math
@direntry
* PSPP: (pspp).             Statistical analysis package.
@end direntry

@copying
This manual is for GNU PSPP version @value{VERSION},
software for statistical analysis.

Copyright @copyright{} 1997, 1998, 2004, 2005, 2009 Free Software Foundation, Inc.

@quotation
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.1 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with the Front-Cover Texts being ``A GNU Manual,''
and with the Back-Cover Texts as in (a) below.  A copy of the
license is included in the section entitled ``GNU Free Documentation
License.''

(a) The FSF's Back-Cover Text is: ``You have the freedom to copy and
modify this GNU manual.''
@end quotation
@end copying

@titlepage
@title PSPP Users Guide
@subtitle GNU PSPP Statistical Analysis Software
@subtitle Release @value{VERSION}
@author
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@chapheading Acknowledgements
The authors wish to thank
Network Theory Ltd 
@url{http://www.network-theory.co.uk}
for their financial support 
in the production of this manual.


@contents


@ifnottex
@node Top
@top GNU PSPP

@insertcopying
@end ifnottex

@menu
* Introduction::                Description of the package.
* License::                     Your rights and obligations.

* Invocation::                  Starting and running PSPP.
* Using PSPP::                  How to use PSPP --- A brief tutorial.
* Language::                    Basics of the PSPP command language.
* Expressions::                 Numeric and string expression syntax.

* Data Input and Output::       Reading data from user files.
* System and Portable File IO:: Reading and writing system & portable files.
* Combining Data Files::        Combining data from multiple files.
* Variable Attributes::         Adjusting and examining variables.
* Data Manipulation::           Simple operations on data.
* Data Selection::              Select certain cases for analysis.
* Conditionals and Looping::    Doing things many times or not at all.
* Statistics::                  Basic statistical procedures.
* Utilities::                   Other commands.

* Not Implemented::             What's not here yet
* Bugs::                        Known problems; submitting bug reports.

* Function Index::              Index of PSPP functions for expressions.
* Command Index::               Index of PSPP procedures.
* Concept Index::               Index of concepts.

* Configuration::               Configuring PSPP.

* GNU Free Documentation License:: License for copying this manual.
@end menu

@include introduction.texi
@include license.texi

@include invoking.texi
@include tutorial.texi
@include language.texi
@include expressions.texi
@include data-io.texi
@include files.texi
@include combining.texi
@include variables.texi
@include transformation.texi
@include data-selection.texi
@include flow-control.texi
@include statistics.texi
@include utilities.texi
@include not-implemented.texi
@include bugs.texi

@include function-index.texi
@include command-index.texi
@include concept-index.texi

@include configuring.texi

@include fdl.texi

@bye

@c Local Variables:
@c use (texinfo-multiple-files-update "pspp.texinfo")  in emacs to keep these files consistent
@c compile-command: "makeinfo pspp.texinfo"
@c End:
