/* Automatically generated by po2tbl.sed from pspp.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"%s: option `%s' is ambiguous\n", 2},
  {"%s: option `--%s' doesn't allow an argument\n", 3},
  {"%s: option `%c%s' doesn't allow an argument\n", 4},
  {"%s: option `%s' requires an argument\n", 5},
  {"%s: unrecognized option `--%s'\n", 6},
  {"%s: unrecognized option `%c%s'\n", 7},
  {"%s: illegal option -- %c\n", 8},
  {"%s: invalid option -- %c\n", 9},
  {"%s: option requires an argument -- %c\n", 10},
  {"OUTFILE specified multiple times.", 11},
  {"while expecting COLUMNWISE", 12},
  {"BREAK specified multiple times.", 13},
  {"BREAK subcommand not specified.", 14},
  {"expecting aggregation function", 15},
  {"Unknown aggregation function %s.", 16},
  {"expecting `('", 17},
  {"Missing argument %d to %s.", 18},
  {"Arguments to %s must be of same type as source variables.", 19},
  {"expecting `)'", 20},
  {"\
Number of source variables (%d) does not match number of target variables \
(%d).", 21},
  {"\
Variable name %s is not unique within the aggregate file dictionary, which \
contains the aggregate variables and the break variables.", 22},
  {"\
A number being treated as a Boolean in an expression was found to have a \
value other than 0 (false), 1 (true), or the system-missing value.  The \
result was forced to 0.", 23},
  {"\
SYSMIS is not a valid index value for vector %s.  The result will be set to \
SYSMIS.", 24},
  {"\
%g is not a valid index value for vector %s.  The result will be set to \
SYSMIS.", 25},
  {"\
SYSMIS is not a valid index value for vector %s.  The result will be set to \
the empty string.", 26},
  {"\
%g is not a valid index value for vector %s.  The result will be set to the \
empty string.", 27},
  {"evaluate_expression(): not implemented: %s\n", 28},
  {"evaluate_expression(): not implemented: %d\n", 29},
  {"\
A string expression was supplied in a place where a Boolean expression was \
expected.", 30},
  {"\
A numeric expression was expected in a place where one was not supplied.", 31},
  {"A string expression was expected in a place where one was not supplied.", 32},
  {"The OR operator cannot take string operands.", 33},
  {"The AND operator cannot take string operands.", 34},
  {"The NOT operator cannot take a string operand.", 35},
  {"\
Strings cannot be compared with numeric or Boolean values with the \
relational operators = >= > <= < <>.", 36},
  {"The `+' and `-' operators may only be used with numeric operands.", 37},
  {"The `*' and `/' operators may only be used with numeric operands.", 38},
  {"The unary minus (-) operator can only take a numeric operand.", 39},
  {"Both operands to the ** operator must be numeric.", 40},
  {"Use of $LENGTH is obsolete, returning default of 66.", 41},
  {"Use of $WIDTH is obsolete, returning default of 131.", 42},
  {"Unknown system variable %s.", 43},
  {"expecting variable name", 44},
  {"in expression", 45},
  {"Argument 2 to LAG must be a small positive integer constant.", 46},
  {"\
Type mismatch in argument %d of %s, which was expected to be of %s type.  It \
was actually of %s type. ", 47},
  {"%s cannot take Boolean operands.", 48},
  {"in function call", 49},
  {"RANGE requires an odd number of arguments, but at least three.", 50},
  {"%s requires at least two arguments.", 51},
  {"%s.%d requires at least %d arguments.", 52},
  {"\
Argument %d to CONCAT is type %s.  All arguments to CONCAT must be strings.", 53},
  {"\
Argument %d to %s was expected to be of %s type.  It was actually of type %s.", 54},
  {"numeric", 55},
  {"string", 56},
  {"%s is not a numeric format.", 57},
  {"Too few arguments to function %s.", 58},
  {"\
Type mismatch in argument %d of %s, which was expected to be numeric.  It \
was actually type %s.", 59},
  {"Missing comma following argument %d of %s.", 60},
  {"The index value after a vector name must be numeric.", 61},
  {"`)' expected after a vector index value.", 62},
  {"There is no function named %s.", 63},
  {"Function %s may not be given a minimum number of arguments.", 64},
  {"expecting `)' after %s function", 65},
  {"error", 66},
  {"Boolean", 67},
  {"!!TERMINAL!!", 68},
  {"!!SENTINEL!!", 69},
  {"!!ERROR%d!!", 70},
  {"postfix:", 71},
  {"\
While optimizing a constant expression, there was a bad value for the third \
argument to INDEX.", 72},
  {"\
While optimizing a constant expression, there was a bad value for the third \
argument to RINDEX.", 73},
  {"Third argument to %cPAD() must be at least one character in length.", 74},
  {"Second argument to %cTRIM() must be at least one character in length.", 75},
  {"\
When optimizing a constant expression, an integer that was being used as an \
Boolean value was found to have a constant value other than 0, 1, or SYSMIS.", 76},
  {"hash table:", 77},
  {"Searching for `%s'...", 78},
  {"Search unsuccessful!", 79},
  {"Found `%s'.", 80},
  {"Not opening pipe file `%s' because SAFER option set.", 81},
  {"Variable %s is %s in target file, but %s in source file.", 82},
  {"Cannot add value labels from source file to long string variable %s.", 83},
  {"\
Cannot apply missing values from source file to long string variable %s.", 84},
  {"No matching variables found between the source and target files.", 85},
  {"bad ordering of keys %d and %d\n", 86},
  {"Heap contents:\n", 87},
  {"data-file error: ", 88},
  {"(column %d", 89},
  {"(columns %d-%d", 90},
  {", field type %s) ", 91},
  {"Field contents followed by garbage.", 92},
  {"Overflow in floating-point constant.", 93},
  {"Underflow in floating-point constant.", 94},
  {"Field does not form a valid floating-point constant.", 95},
  {"All characters in field must be digits.", 96},
  {"Unrecognized character in field.", 97},
  {"Field must have even length.", 98},
  {"Field must contain only hex digits.", 99},
  {"\
Quality of zoned decimal (Z) input format code is suspect.  Check your \
results three times, report bugs to author.", 100},
  {"Zoned decimal field contains fewer than 2 characters.", 101},
  {"Bad sign byte in zoned decimal number.", 102},
  {"Format error in zoned decimal number.", 103},
  {"Error in syntax of zoned decimal number.", 104},
  {"Unexpected end of field.", 105},
  {"Digit expected in field.", 106},
  {"Day (%ld) must be between 1 and 31.", 107},
  {"Delimiter expected between fields in date.", 108},
  {"Month (%ld) must be between 1 and 12.", 109},
  {"Month (%s) must be between I and XII.", 110},
  {"Month name (%s...) is too long.", 111},
  {"Bad month name (%s).", 112},
  {"Year (%ld) must be between 1582 and 19999.", 113},
  {"Trailing garbage \"%s\" following date.", 114},
  {"Julian day (%d) must be between 1 and 366.", 115},
  {"Year (%d) must be between 1582 and 19999.", 116},
  {"Quarter (%ld) must be between 1 and 4.", 117},
  {"`Q' expected between quarter and year.", 118},
  {"Week (%ld) must be between 1 and 53.", 119},
  {"`WK' expected between week and year.", 120},
  {"Delimiter expected between fields in time.", 121},
  {"Hour (%ld) must be positive.", 122},
  {"Minute (%ld) must be between 0 and 59.", 123},
  {"Hour (%ld) must be between 0 and 23.", 124},
  {"Day of the week expected in date value.", 125},
  {"Date is not in valid range between 15 Oct 1582 and 31 Dec 19999.", 126},
  {"Field too long (%d characters).  Truncated after character %d.", 127},
  {"\
DATA LIST may not use a different file from that specified on its \
surrounding FILE TYPE.", 128},
  {"The END subcommand may only be specified once.", 129},
  {"Only one of FIXED, FREE, or LIST may be specified.", 130},
  {"\
The record number specified, %ld, is before the previous record, %d.  Data \
fields must be listed in order of increasing record number.", 131},
  {"\
SPSS-like or FORTRAN-like format specification expected after variable names.", 132},
  {"\
Variables are specified on records that should not exist according to \
RECORDS subcommand.", 133},
  {"expecting end of command", 134},
  {"Column positions for fields must be positive.", 135},
  {"The ending column for a field must be greater than the starting column.", 136},
  {"A format specifier on this line has extra characters on the end.", 137},
  {"The value for number of decimal places must be at least 1.", 138},
  {"Input format %s doesn't accept decimal places.", 139},
  {"The %d columns %d-%d can't be evenly divided into %d fields.", 140},
  {"%s is a duplicate variable name.", 141},
  {"There is already a variable %s of a different type.", 142},
  {"There is already a string variable %s of a different width.", 143},
  {"\
The number of format specifications exceeds the number of variable names \
given.", 144},
  {"\
There aren't enough format specifications to match the number of variable \
names given.", 145},
  {"Variable", 146},
  {"Record", 147},
  {"Columns", 148},
  {"Format", 149},
  {"Reading %d record%s from file %s.", 150},
  {"Reading %d record%s from the command file.", 151},
  {"Occurrence data specifications.", 152},
  {"Reading free-form data from file %s.", 153},
  {"Reading free-form data from the command file.", 154},
  {"Scope of string exceeds line.", 155},
  {"Attempt to read past end of file.", 156},
  {"abort in write_case()\n", 157},
  {"Partial case of %d of %d records discarded.", 158},
  {"Partial case discarded.  The first variable missing was %s.", 159},
  {"\
Missing value(s) for all variables from %s onward.  These will be filled \
with the system-missing value or blanks, as appropriate.", 160},
  {"\
REPEATING DATA must use the same file as its corresponding DATA LIST or FILE \
TYPE.", 161},
  {"STARTS subcommand given multiple times.", 162},
  {"STARTS beginning column (%d) exceeds STARTS ending column (%d).", 163},
  {"OCCURS subcommand given multiple times.", 164},
  {"LENGTH subcommand given multiple times.", 165},
  {"CONTINUED subcommand given multiple times.", 166},
  {"CONTINUED beginning column (%d) exceeds CONTINUED ending column (%d).", 167},
  {"ID subcommand given multiple times.", 168},
  {"ID beginning column (%ld) must be positive.", 169},
  {"ID ending column (%ld) must be positive.", 170},
  {"ID ending column (%ld) cannot be less than ID beginning column (%d).", 171},
  {"Missing required specification STARTS.", 172},
  {"Missing required specification OCCURS.", 173},
  {"ID specified without CONTINUED.", 174},
  {"String variable not allowed here.", 175},
  {"%s (%d) must be at least 1.", 176},
  {"Variable or integer expected for %s.", 177},
  {"Mismatched case ID (%s).  Expected value was %s.", 178},
  {"\
Variable %s startging in column %d extends beyond physical record length of \
%d.", 179},
  {"Invalid value %d for OCCURS.", 180},
  {"Beginning column for STARTS (%d) must be at least 1.", 181},
  {"Ending column for STARTS (%d) is less than beginning column (%d).", 182},
  {"Invalid value %d for LENGTH.", 183},
  {"Beginning column for CONTINUED (%d) must be at least 1.", 184},
  {"Ending column for CONTINUED (%d) is less than beginning column (%d).", 185},
  {"\
Number of repetitions specified on OCCURS (%d) exceed number of repetitions \
available in space on STARTS (%d), and CONTINUED not specified.", 186},
  {"Unexpected end of file with %d repetitions remaining out of %d.", 187},
  {"%s: Closing data-file handle %s.", 188},
  {"<<Bug in dfm.c>>", 189},
  {"%s: Opening data-file handle %s for reading.", 190},
  {"BEGIN DATA expected.", 191},
  {"An error occurred while opening \"%s\" for reading as a data file: %s.", 192},
  {"%s: Opening data-file handle %s for writing.", 193},
  {"Cannot open the inline file for writing.", 194},
  {"An error occurred while opening \"%s\" for writing as a data file: %s.", 195},
  {"\
Unexpected end-of-file while reading data in BEGIN DATA.  This probably \
indicates a missing or misformatted END DATA command.  END DATA must appear \
by itself on a single line with exactly one space between words.", 196},
  {"Error reading file %s: %s.", 197},
  {"%s: Partial record at end of file.", 198},
  {"Cannot read from file %s already opened for %s.", 199},
  {"Attempt to read beyond end-of-file on file %s.", 200},
  {"Cannot write to file %s already opened for %s.", 201},
  {"Error writing file %s: %s.", 202},
  {"\
This command is not valid here since the current input program does not \
access the inline file.", 203},
  {"inline file: Opening for reading.", 204},
  {"Skipping remaining inline data.", 205},
  {"reading as a data file", 206},
  {"writing as a data file", 207},
  {"\
File handle %s had already been defined to refer to file %s.  It is not \
possible to redefine a file handle within a session.", 208},
  {"The FILE HANDLE required subcommand NAME is not present.", 209},
  {"\
Fixed length records were specified on /RECFORM, but record length was not \
specified on /LRECL.  80-character records will be assumed.", 210},
  {"\
Record length (%ld) must be at least one byte.  80-character records will be \
assumed.", 211},
  {"\
/RECFORM SPANNED is not implemented, as the author doesn't know what it is \
supposed to do.  Send the author a note.", 212},
  {"\
/MODE IMAGE is not implemented, as the author doesn't know what it is \
supposed to do.  Send the author a note.", 213},
  {"/MODE MULTIPUNCH is not implemented.  If you care, complain.", 214},
  {"/MODE 360 is not implemented.  If you care, complain.", 215},
  {"File handle `%s' has not been previously declared on FILE HANDLE.", 216},
  {"<Inline File>", 217},
  {"expecting a file name or handle", 218},
  {"MIXED, GROUPED, or NESTED expected.", 219},
  {"The CASE subcommand is not valid on FILE TYPE MIXED.", 220},
  {"WARN or NOWARN expected after WILD.", 221},
  {"The DUPLICATE subcommand is not valid on FILE TYPE MIXED.", 222},
  {"DUPLICATE=CASE is only valid on FILE TYPE NESTED.", 223},
  {"WARN%s expected after DUPLICATE.", 224},
  {", NOWARN, or CASE", 225},
  {" or NOWARN", 226},
  {"The MISSING subcommand is not valid on FILE TYPE MIXED.", 227},
  {"WARN or NOWARN after MISSING.", 228},
  {"ORDERED is only valid on FILE TYPE GROUPED.", 229},
  {"YES or NO expected after ORDERED.", 230},
  {"while expecting a valid subcommand", 231},
  {"The required RECORD subcommand was not present.", 232},
  {"The required CASE subcommand was not present.", 233},
  {"CASE and RECORD must specify different variable names.", 234},
  {"Column value must be positive.", 235},
  {"Ending column precedes beginning column.", 236},
  {"Bad format specifier name.", 237},
  {"\
This command may only appear within a FILE TYPE/END FILE TYPE structure.", 238},
  {"OTHER may appear only on the last RECORD TYPE command.", 239},
  {"No input commands (DATA LIST, REPEATING DATA) for above RECORD TYPE.", 240},
  {"\
The CASE subcommand is not allowed on the RECORD TYPE command for FILE TYPE \
MIXED.", 241},
  {"\
No variable name may be specified for the CASE subcommand on RECORD TYPE.", 242},
  {"\
The CASE column specification on RECORD TYPE must give a format specifier \
that is the same type as that of the CASE column specification given on FILE \
TYPE.", 243},
  {"WARN or NOWARN expected on DUPLICATE subcommand.", 244},
  {"WARN or NOWARN expected on MISSING subcommand.", 245},
  {"YES or NO expected on SPREAD subcommand.", 246},
  {"No input commands (DATA LIST, REPEATING DATA) on above RECORD TYPE.", 247},
  {"No commands between FILE TYPE and END FILE TYPE.", 248},
  {"Unknown record type \"%.*s\".", 249},
  {"Unknown record type %g.", 250},
  {"X and T format specifiers not allowed here.", 251},
  {"%s is not a valid data format.", 252},
  {"Format %s may not be used as an input format.", 253},
  {"\
Input format %s specifies a bad width %d.  Format %s requires a width \
between %d and %d.", 254},
  {"\
Input format %s specifies an odd width %d, but format %s requires an even \
width between %d and %d.", 255},
  {"\
Input format %s specifies a bad number of implied decimal places %d.  Input \
format %s allows up to 16 implied decimal places.", 256},
  {"\
Output format %s specifies a bad width %d.  Format %s requires a width \
between %d and %d.", 257},
  {"\
Output format %s requires minimum width %d to allow %d decimal places.  Try \
%s%d.%d instead of %s.", 258},
  {"\
Output format %s specifies an odd width %d, but output format %s requires an \
even width between %d and %d.", 259},
  {"\
Output format %s specifies a bad number of implied decimal places %d.  \
Output format %s allows a number of implied decimal places between 1 and 16.", 260},
  {"Can't display a string variable of width %d with format specifier %s.", 261},
  {"Format specifier expected.", 262},
  {"Data format %s does not specify a width.", 263},
  {"Data format %s is not valid.", 264},
  {"`(' expected after variable list", 265},
  {"Format %s may not be assigned to a %s variable.", 266},
  {"`)' expected after output format.", 267},
  {"Formats:\n", 268},
  {"  Name      Print         Write\n", 269},
  {"GET translation table from file to memory:\n", 270},
  {"  %8s from %3d,%3d to %3d,%3d\n", 271},
  {"All variables deleted from system file dictionary.", 272},
  {"\
Cannot rename %s as %s because there already exists a variable named %s.  To \
rename variables with overlapping names, use a single RENAME subcommand such \
as \"/RENAME (A=B)(B=C)(C=A)\", or equivalently, \"/RENAME (A B C=B C A)\".", 273},
  {"`=' expected after variable list.", 274},
  {"\
Number of variables on left side of `=' (%d) do not match number of \
variables on right side (%d), in parenthesized group %d of RENAME subcommand.", 275},
  {"Duplicate variables name %s.", 276},
  {"\
\n\
Variables in dictionary:\n", 277},
  {"The BY subcommand may be given once at most.", 278},
  {"The active file may not be specified more than once.", 279},
  {"Cannot specify the active file since no active file has been defined.", 280},
  {"\
IN, FIRST, and LAST subcommands may not occur before the first FILE or TABLE.", 281},
  {"Multiple %s subcommands for a single FILE or TABLE.", 282},
  {"Duplicate variable name %s while creating %s variable.", 283},
  {"\
RENAME, KEEP, and DROP subcommands may not occur before the first FILE or \
TABLE.", 284},
  {"The BY subcommand is required when a TABLE subcommand is given.", 285},
  {"File %s lacks BY variable %s.", 286},
  {"\
Variable %s in file %s (%s) has different type or width from the same \
variable in earlier file (%s).", 287},
  {"expecting COMM or TAPE", 288},
  {"IMPORT translation table from file to memory:\n", 289},
  {"No matching INPUT PROGRAM command.", 290},
  {"\
No data-input or transformation commands specified between INPUT PROGRAM and \
END INPUT PROGRAM.", 291},
  {"\
This command may only be executed between INPUT PROGRAM and END INPUT \
PROGRAM.", 292},
  {"COLUMN subcommand multiply specified.", 293},
  {"expecting file handle name", 294},
  {"\
REREAD: Column numbers must be positive finite numbers.  Column set to 1.", 295},
  {"VARIABLES subcommand multiply specified.", 296},
  {"VARNAME_ cannot be explicitly specified on VARIABLES.", 297},
  {"in FORMAT subcommand", 298},
  {"SPLIT subcommand multiply specified.", 299},
  {"in SPLIT subcommand", 300},
  {"Split variable may not be named ROWTYPE_ or VARNAME_.", 301},
  {"Split variable %s is already another type.", 302},
  {"FACTORS subcommand multiply specified.", 303},
  {"Factor variable %s is already another type.", 304},
  {"CELLS subcommand multiply specified.", 305},
  {"expecting positive integer", 306},
  {"N subcommand multiply specified.", 307},
  {"CONTENTS subcommand multiply specified.", 308},
  {"Nested parentheses not allowed.", 309},
  {"Mismatched right parenthesis (`(').", 310},
  {"Empty parentheses not allowed.", 311},
  {"in CONTENTS subcommand", 312},
  {"Content multiply specified for %s.", 313},
  {"Missing right parenthesis.", 314},
  {"Missing VARIABLES subcommand.", 315},
  {"\
CONTENTS subcommand not specified: assuming file contains only CORR matrix.", 316},
  {"\
Missing CELLS subcommand.  CELLS is required when ROWTYPE_ is not given in \
the data and factors are present.", 317},
  {"Split file values must be present in the data when ROWTYPE_ is present.", 318},
  {"No continuous variables specified.", 319},
  {"End of line expected %s while reading %s.", 320},
  {"expecting value for %s %s", 321},
  {"Syntax error expecting SPLIT FILE value %s.", 322},
  {"Expecting value %g for %s.", 323},
  {"Syntax error expecting factor value %s.", 324},
  {"Syntax error expecting value %g for %s %s.", 325},
  {"Syntax error %s expecting SPLIT FILE value.", 326},
  {"\
Expected %d lines of data for %s content; actually saw %d lines.  No data \
will be output for this content.", 327},
  {"Multiply specified ROWTYPE_ %s.", 328},
  {"Syntax error %s expecting ROWTYPE_ string.", 329},
  {"Syntax error %s.", 330},
  {"Duplicate specification for %s.", 331},
  {"Too many rows of matrix data for %s.", 332},
  {"Syntax error expecting value for %s %s.", 333},
  {"portable file %s corrupt at offset %ld: ", 334},
  {"%s: Closing portable file: %s.", 335},
  {"Unexpected end of file.", 336},
  {"Bad line end.", 337},
  {"Cannot read file %s as portable file: already opened for %s.", 338},
  {"%s: Opening portable-file handle %s for reading.", 339},
  {"\
An error occurred while opening \"%s\" for reading as a portable file: %s.", 340},
  {"Data record expected.", 341},
  {"Read portable-file dictionary successfully.", 342},
  {"Error reading portable-file dictionary.", 343},
  {"Missing numeric terminator.", 344},
  {"Bad integer format.", 345},
  {"Bad string length %d.", 346},
  {"Bad date string length %d.", 347},
  {"Bad character in date.", 348},
  {"Bad time string length %d.", 349},
  {"Bad character in time.", 350},
  {"%s: Bad format specifier byte %d.", 351},
  {"%s: Bad format specifier byte (%d).", 352},
  {"%s variable %s has %s format specifier %s.", 353},
  {"String", 354},
  {"Numeric", 355},
  {"Expected variable count record.", 356},
  {"Invalid number of variables %d.", 357},
  {"Unexpected flag value %d.", 358},
  {"Expected variable record.", 359},
  {"Invalid variable width %d.", 360},
  {"position %d: Variable name has %u characters.", 361},
  {"position %d: Variable name begins with invalid character.", 362},
  {"position %d: Variable name begins with lowercase letter %c.", 363},
  {"position %d: Variable name character %d is lowercase letter %c.", 364},
  {"position %d: character `\\%03o' is not valid in a variable name.", 365},
  {"Duplicate variable name %s.", 366},
  {"Bad missing values for %s.", 367},
  {"Weighting variable %s not present in dictionary.", 368},
  {"Unknown variable %s while parsing value labels.", 369},
  {"\
Cannot assign value labels to %s and %s, which have different variable types \
or widths.", 370},
  {"Duplicate label for value %g for variable %s.", 371},
  {"Duplicate label for value `%.*s' for variable %s.", 372},
  {"End of file midway through case.", 373},
  {"reading as a portable file", 374},
  {"Cannot write file %s as portable file: already opened for %s.", 375},
  {"%s: Opening portable-file handle %s for writing.", 376},
  {"\
An error occurred while opening \"%s\" for writing as a portable file: %s.", 377},
  {"Wrote portable-file header successfully.", 378},
  {"Error writing portable-file header.", 379},
  {"%s: Writing portable file: %s.", 380},
  {"writing as a portable file", 381},
  {"corrupt system file: ", 382},
  {"%s: Closing system file: %s.", 383},
  {"Cannot read file %s as system file: already opened for %s.", 384},
  {"%s: Opening system-file handle %s for reading.", 385},
  {"\
An error occurred while opening \"%s\" for reading as a system file: %s.", 386},
  {"\
%s: Weighting variable may not be a continuation of a long string variable.", 387},
  {"%s: Weighting variable may not be a string variable.", 388},
  {"\
%s: Orphaned variable index record (type 4).  Type 4 records must always \
immediately follow type 3 records.", 389},
  {"%s: Unrecognized record type 7, subtype %d encountered in system file.", 390},
  {"%s: Unrecognized record type %d.", 391},
  {"Read system-file dictionary successfully.", 392},
  {"Error reading system-file header.", 393},
  {"\
%s: Bad size (%d) or count (%d) field on record type 7, subtype 3.\tExpected \
size %d, count 8.", 394},
  {"\
%s: Floating-point representation in system file is not IEEE-754.  PSPP \
cannot convert between floating-point formats.", 395},
  {"\
%s: File-indicated endianness (%s) does not match endianness intuited from \
file header (%s).", 396},
  {"big-endian", 397},
  {"little-endian", 398},
  {"unknown", 399},
  {"%s: File-indicated character representation code (%s) is not ASCII.", 400},
  {"DEC Kanji", 401},
  {"Unknown", 402},
  {"\
%s: Bad size (%d) or count (%d) field on record type 7, subtype 4.\tExpected \
size %d, count 8.", 403},
  {"\
%s: File-indicated value is different from internal value for at least one \
of the three system values.  SYSMIS: indicated %g, expected %g; HIGHEST: %g, \
%g; LOWEST: %g, %g.", 404},
  {"\
%s: Bad magic.  Proper system files begin with the four characters `$FL2'. \
This file will not be read.", 405},
  {"\
%s: File layout code has unexpected value %d.  Value should be 2, in \
big-endian or little-endian format.", 406},
  {"%s: Number of elements per case (%d) is not between 1 and %d.", 407},
  {"\
%s: Index of weighting variable (%d) is not between 0 and number of elements \
per case (%d).", 408},
  {"%s: Number of cases in file (%ld) is not between -1 and %d.", 409},
  {"%s: Compression bias (%g) is not the usual value of 100.", 410},
  {"%s: position %d: Bad record type (%d); the expected value was 2.", 411},
  {"\
%s: position %d: String variable does not have proper number of continuation \
records.", 412},
  {"%s: position %d: Superfluous long string continuation record.", 413},
  {"%s: position %d: Bad variable type code %d.", 414},
  {"%s: position %d: Variable label indicator field is not 0 or 1.", 415},
  {"\
%s: position %d: Missing value indicator field is not -3, -2, 0, 1, 2, or 3.", 416},
  {"%s: position %d: Variable name begins with invalid character.", 417},
  {"%s: position %d: Variable name begins with lowercase letter %c.", 418},
  {"\
%s: position %d: Variable name begins with octothorpe (`#').  Scratch \
variables should not appear in system files.", 419},
  {"%s: position %d: Variable name character %d is lowercase letter %c.", 420},
  {"\
%s: position %d: character `\\%03o' (%c) is not valid in a variable name.", 421},
  {"%s: Variable %s indicates variable label of invalid length %d.", 422},
  {"%s: Long string variable %s may not have missing values.", 423},
  {"\
%s: String variable %s may not have missing values specified as a range.", 424},
  {"%s: Long string continuation records omitted at end of dictionary.", 425},
  {"\
%s: System file header indicates %d variable positions but %d were read from \
file.", 426},
  {"%s: Duplicate variable name `%s' within system file.", 427},
  {"%s: %s variable %s has %s format specifier %s.", 428},
  {"\
%s: Variable index record (type 4) does not immediately follow value label \
record (type 3) as it ought.", 429},
  {"\
%s: Number of variables associated with a value label (%d) is not between 1 \
and the number of variables (%d).", 430},
  {"\
%s: Variable index associated with value label (%d) is not between 1 and the \
number of values (%d).", 431},
  {"\
%s: Variable index associated with value label (%d) refers to a continuation \
of a string variable, not to an actual variable.", 432},
  {"%s: Value labels are not allowed on long string variables (%s).", 433},
  {"\
%s: Variables associated with value label are not all of identical type.  \
Variable %s has %s type, but variable %s has %s type.", 434},
  {"%s: File contains duplicate label for value %g for variable %s.", 435},
  {"%s: File contains duplicate label for value `%.*s' for variable %s.", 436},
  {"%s: Reading system file: %s.", 437},
  {"%s: Unexpected end of file.", 438},
  {"%s: System file contains multiple type 6 (document) records.", 439},
  {"%s: Number of document lines (%ld) must be greater than 0.", 440},
  {"dictionary:\n", 441},
  {"num", 442},
  {"str", 443},
  {"left", 444},
  {"right", 445},
  {"none", 446},
  {"one", 447},
  {"two", 448},
  {"three", 449},
  {"range", 450},
  {"low", 451},
  {"high", 452},
  {"range+1", 453},
  {"low+1", 454},
  {"high+1", 455},
  {"%s: Error reading file: %s.", 456},
  {"%s: Compressed data is corrupted.  Data ends partway through a case.", 457},
  {"%s: Partial record at end of system file.", 458},
  {"reading as a system file", 459},
  {"Cannot write file %s as system file: already opened for %s.", 460},
  {"%s: Opening system-file handle %s for writing.", 461},
  {"\
An error occurred while opening \"%s\" for writing as a system file: %s.", 462},
  {"Wrote system-file header successfully.", 463},
  {"Error writing system-file header.", 464},
  {"%s: Writing system file: %s.", 465},
  {"writing as a system file", 466},
  {"File:", 467},
  {"Label:", 468},
  {"No label.", 469},
  {"Created:", 470},
  {"Endian:", 471},
  {"Big.", 472},
  {"Little.", 473},
  {"<internal error>", 474},
  {"Variables:", 475},
  {"Cases:", 476},
  {"Type:", 477},
  {"System File.", 478},
  {"Weight:", 479},
  {"Not weighted.", 480},
  {"Mode:", 481},
  {"Compression %s.", 482},
  {"on", 483},
  {"off", 484},
  {"Description", 485},
  {"Position", 486},
  {"The active file does not have a file label.", 487},
  {"File label:", 488},
  {"No variables to display.", 489},
  {"Macros not supported.", 490},
  {"The active file dictionary does not contain any documents.", 491},
  {"Documents in the active file:", 492},
  {"Label", 493},
  {"Format: %s", 494},
  {"Print Format: %s", 495},
  {"Write Format: %s", 496},
  {"Missing Values: ", 497},
  {"Value", 498},
  {"No vectors defined.", 499},
  {"Vector", 500},
  {"%s not allowed inside FILE TYPE/END FILE TYPE.", 501},
  {"%s not allowed inside FILE TYPE GROUPED/END FILE TYPE.", 502},
  {"RECORD TYPE must be the first command inside a FILE TYPE structure.", 503},
  {"This line does not begin with a valid command name.", 504},
  {"%s is not yet implemented.", 505},
  {"\
%s is not allowed (1) before a command to specify the input program, such as \
DATA LIST, (2) between FILE TYPE and END FILE TYPE, (3) between INPUT \
PROGRAM and END INPUT PROGRAM.", 506},
  {"%s is not allowed within an input program.", 507},
  {"%s is only allowed within an input program.", 508},
  {"%s command beginning\n", 509},
  {"\
%s command completed\n\
\n", 510},
  {"The identifier(s) specified do not form a valid command name:", 511},
  {"The identifier(s) specified do not form a complete command name:", 512},
  {"\
This command is not accepted in a syntax file.  Instead, use FINISH to \
terminate a syntax file.", 513},
  {"\
This command is not executed in interactive mode.  Instead, PSPP drops down \
to the command prompt.  Use EXIT if you really want to quit.", 514},
  {"The sentinel may not be the empty string.", 515},
  {"This command not allowed when the SAFER option is set.", 516},
  {"Error removing `%s': %s.", 517},
  {"Couldn't fork: %s.", 518},
  {"Error executing command: %s.", 519},
  {"No operating system support for this command.", 520},
  {"This command is not valid in a syntax file.", 521},
  {"Can't find `%s' in include file search path.", 522},
  {"%s: Opening as syntax file.", 523},
  {"Opening `%s': %s.", 524},
  {"Reading `%s': %s.", 525},
  {"Closing `%s': %s.", 526},
  {"%s does not form a valid number.", 527},
  {"Bad character in input: `%c'.", 528},
  {"Bad character in input: `\\%o'.", 529},
  {"Syntax error at end of file.", 530},
  {"Syntax error %s at `%s'.", 531},
  {"Syntax error at `%s'.", 532},
  {"expecting `%s'", 533},
  {"expecting %s", 534},
  {"expecting string", 535},
  {"expecting integer", 536},
  {"expecting number", 537},
  {"expecting identifier", 538},
  {"The rest of this command has been discarded.", 539},
  {"<ERROR>", 540},
  {"binary", 541},
  {"octal", 542},
  {"hex", 543},
  {"String of %s digits has %d characters, which is not a multiple of %d.", 544},
  {"`%c' is not a valid %s digit.", 545},
  {"Unterminated string constant.", 546},
  {"String exceeds 255 characters in length (%d characters).", 547},
  {"\
Sorry, literal strings may not contain null characters.  Replacing with \
spaces.", 548},
  {"-f not yet implemented\n", 549},
  {"-n not yet implemented\n", 550},
  {"-p not yet implemented\n", 551},
  {"\
\n\
Copyright (C) 1997-9, 2000 Free Software Foundation, Inc.\n\
This is free software; see the source for copying conditions.  There is NO\n\
WARRANTY; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.\n\
\n\
Written by Ben Pfaff <blp@gnu.org>.", 552},
  {"\
PSPP, a program for statistical analysis of sample data.\n\
\n\
Usage: %s [OPTION]... FILE...\n\
\n\
If a long option shows an argument as mandatory, then it is mandatory\n\
for the equivalent short option also.  Similarly for optional arguments.\n\
\n\
Configuration:\n\
  -B, --config-dir=DIR      set configuration directory to DIR\n\
  -o, --device=DEVICE       select output driver DEVICE and disable \
defaults\n\
  -d, --define=VAR[=VALUE]  set environment variable VAR to VALUE, or empty\n\
  -u, --undef=VAR           undefine environment variable VAR\n\
\n\
Input and output:\n\
  -f, --out-file=FILE       send output to FILE (overwritten)\n\
  -p, --pipe                read script from stdin, send output to stdout\n\
  -I-, --no-include         clear include path\n\
  -I, --include=DIR         append DIR to include path\n\
  -c, --command=COMMAND     execute COMMAND before .pspp/rc at startup\n\
\n\
Language modifiers:\n\
  -i, --interactive         interpret scripts in interactive mode\n\
  -n, --edit                just check syntax; don't actually run the code\n\
  -r, --no-statrc           disable execution of .pspp/rc at startup\n\
  -s, --safer               don't allow some unsafe operations\n\
\n\
Informative output:\n\
  -h, --help                print this help, then exit\n\
  -l, --list                print a list of known driver classes, then exit\n\
  -V, --version             show PSPP version, then exit\n\
  -v, --verbose             increments verbosity level\n\
\n\
Non-option arguments:\n\
 FILE1 FILE2                run FILE1, clear the dictionary, run FILE2\n\
 FILE1 + FILE2              run FILE1 then FILE2 without clearing \
dictionary\n\
 KEY=VALUE                  overrides macros in output initialization file\n\
\n", 553},
  {"\
\n\
Report bugs to <bug-gnu-pspp@gnu.org>.\n", 554},
  {"Terminating NOW due to a fatal error!", 555},
  {"Terminating execution of syntax file due to error.", 556},
  {"Errors (%d) exceeds limit (%d).", 557},
  {"Warnings (%d) exceed limit (%d).", 558},
  {"fatal", 559},
  {"warning", 560},
  {"note", 561},
  {"installation error", 562},
  {"\
\n\
\t*********************\n\
\t* INDUCING SEGFAULT *\n\
\t*********************\n", 563},
  {"\
Your machine does not appear to be either big- or little-endian.  At the \
moment, PSPP only supports machines of these standard endiannesses.  If you \
want to hack in others, contact the author.", 564},
  {"data> ", 565},
  {"Specify a terminal type with `setenv TERM <yourtype>'.", 566},
  {"Could not access the termcap data base.", 567},
  {"Terminal type `%s' is not defined.", 568},
  {"Assuming screen of size 79x25.", 569},
  {"Jan", 570},
  {"Feb", 571},
  {"Mar", 572},
  {"Apr", 573},
  {"May", 574},
  {"Jun", 575},
  {"Jul", 576},
  {"Aug", 577},
  {"Sep", 578},
  {"Oct", 579},
  {"Nov", 580},
  {"Dec", 581},
  {"Error initializing output drivers.", 582},
  {"This command not executed.", 583},
  {"\
Skipping the rest of this command.  Part of this command may have been \
executed.", 584},
  {"\
Skipping the rest of this command.  This command was fully executed up to \
this point.", 585},
  {"\
Trailing garbage was encountered following this command.  The command was \
fully executed to this point.", 586},
  {"ASCII driver initializing as `%s'...", 587},
  {"\
ascii driver: Area of page excluding margins and headers must be at least 59 \
characters wide by 15 lines long.  Page as configured is only %d characters \
by %d lines.", 588},
  {"%s: Initialization complete.", 589},
  {"%s: Beginning closing...", 590},
  {"%s: Finished closing.", 591},
  {"\
Bad index value for `box' key: syntax is box[INDEX], 0 <= INDEX < %d \
decimal, with INDEX expressed in base 4.", 592},
  {"Duplicate value for key `%s'.", 593},
  {"Unknown configuration parameter `%s' for ascii device driver.", 594},
  {"\
Unknown character set `%s'.  Valid character sets are `ascii' and `latin1'.", 595},
  {"\
Unknown overstrike style `%s'.  Valid overstrike styles are `single' and \
`line'.", 596},
  {"\
Unknown carriage return style `%s'.  Valid carriage return styles are `cr' \
and `bs'.", 597},
  {"Positive integer required as value for `%s'.", 598},
  {"Zero or positive integer required as value for `%s'.", 599},
  {"Boolean value expected for %s.", 600},
  {"ASCII output driver: %s: %s", 601},
  {"ascii_line_horz: bad hline (%d,%d),%d out of (%d,%d)\n", 602},
  {"ascii_line_vert: bad vline %d,(%d,%d) out of (%d,%d)\n", 603},
  {"ascii_line_intersection: bad intsct (%d,%d) out of (%d,%d)\n", 604},
  {"%s: horiz=%d, vert=%d\n", 605},
  {"Writing `%s': %s", 606},
  {"%s - Page %d", 607},
  {"\
The N output format cannot be used to output a negative number or the \
system-missing value.", 608},
  {"\
Quality of zoned decimal (Z) output format code is suspect.  Check your \
results, report bugs to author.", 609},
  {"The system-missing value cannot be output as a zoned decimal number.", 610},
  {"Number %g too big to fit in field with format Z%d.%d.", 611},
  {"Time value %g too large in magnitude to convert to alphanumeric time.", 612},
  {"Weekday index %d does not lie between 1 and 7.", 613},
  {"Month index %d does not lie between 1 and 12.", 614},
  {"\
Year %d cannot be represented in four digits for output formatting purposes.", 615},
  {"%s: Opening Groff font file...", 616},
  {"Missing font name.", 617},
  {"Missing encoding filename.", 618},
  {"Bad spacewidth value.", 619},
  {"Bad slant value.", 620},
  {"Unknown ligature `%s'.", 621},
  {"Unexpected end of line reading character set.", 622},
  {"Can't use ditto mark for first character.", 623},
  {"Can't ditto into an unnamed character.", 624},
  {"Missing metrics for character `%s'.", 625},
  {"Missing type for character `%s'.", 626},
  {"Missing code for character `%s'.", 627},
  {"Malformed kernpair.", 628},
  {"Unexpected end of line reading kernpairs.", 629},
  {"Bad kern value.", 630},
  {"Font read successfully with internal name %s.", 631},
  {"Error reading font.", 632},
  {"installation error: Groff font error: ", 633},
  {"Bad character \\%3o.", 634},
  {"Groff font error: Cannot find \"%s\".", 635},
  {"%s: Opening Groff description file...", 636},
  {"Multiple `sizes' declarations.", 637},
  {"Unexpected end of file.  Missing 0 terminator to `sizes' command?", 638},
  {"Bad argument to `sizes'.", 639},
  {"Bad range in argument to `sizes'.", 640},
  {"Family name expected.", 641},
  {"This command already specified.", 642},
  {"%s: Device characteristic already defined.", 643},
  {"%s: Invalid numeric format.", 644},
  {"Missing `res', `unitwidth', and/or `sizes' line(s).", 645},
  {"Description file read successfully.", 646},
  {"Error reading description file.", 647},
  {"<<fallback>>", 648},
  {"HTML driver initializing as `%s'...", 649},
  {"Unknown configuration parameter `%s' for HTML device driver.", 650},
  {"\
Cannot find HTML prologue.  The use of `-vv' on the command line is \
suggested as a debugging aid.", 651},
  {"%s: %s: Opening HTML prologue...", 652},
  {"nobody", 653},
  {"nowhere", 654},
  {"%s: HTML prologue read successfully.", 655},
  {"%s: Error reading HTML prologue.", 656},
  {"HTML output driver: %s: %s", 657},
  {"Cannot open first page on HTML device %s.", 658},
  {"Unknown output driver `%s'.", 659},
  {"Output driver `%s' referenced but never defined.", 660},
  {"Cannot find output initialization file.  Use `-vv' to view search path.", 661},
  {"%s: Opening device description file...", 662},
  {"Opening %s: %s.", 663},
  {"Reading %s: %s.", 664},
  {"Syntax error.", 665},
  {"Closing %s: %s.", 666},
  {"No output drivers are active.", 667},
  {"Device definition file read successfully.", 668},
  {"Error reading device definition file.", 669},
  {"\
Driver classes:\n\
\t", 670},
  {"Syntax error in string constant.", 671},
  {"Syntax error in options.", 672},
  {"Syntax error in options (`=' expected).", 673},
  {"Syntax error in options (value expected after `=').", 674},
  {"Driver name expected.", 675},
  {"Class name expected.", 676},
  {"Unknown output driver class `%s'.", 677},
  {"Can't initialize output driver class `%s'.", 678},
  {"Can't initialize output driver `%s' of class `%s'.", 679},
  {"Unknown device type `%s'.", 680},
  {"Can't complete initialization of output driver `%s' of class `%s'.", 681},
  {"Can't deinitialize output driver class `%s'.", 682},
  {"Trying to find keyword `%s'...\n", 683},
  {"Unit \"%s\" is unknown in dimension \"%s\".", 684},
  {"Bad dimension \"%s\".", 685},
  {"`x' expected in paper size `%s'.", 686},
  {"Trailing garbage `%s' on paper size `%s'.", 687},
  {"Paper size name must not be empty.", 688},
  {"Cannot find `papersize' configuration file.", 689},
  {"%s: Opening paper size definition file...", 690},
  {"Syntax error in paper size definition.", 691},
  {"Paper size definition file read successfully.", 692},
  {"Error reading paper size definition file.", 693},
  {"Error closing page on %s device of %s class.", 694},
  {"Error opening page on %s device of %s class.", 695},
  {"PostScript driver initializing as `%s'...", 696},
  {"\
PostScript driver: The defined page is not long enough to hold margins and \
headers, plus least 15 lines of the default fonts.  In fact, there's only \
room for %d lines of each font at the default size of %d.%03d points.", 697},
  {"Unknown configuration parameter `%s' for PostScript device driver.", 698},
  {"\
Unknown orientation `%s'.  Valid orientations are `portrait' and `landscape'.", 699},
  {"\
Unknown value for `data'.  Valid values are `clean7bit', `clean8bit', and \
`binary'.", 700},
  {"Unknown value for `line-ends'.  Valid values are `lf' and `crlf'.", 701},
  {"Unknown value for `line-style'.  Valid values are `thick' and `double'.", 702},
  {"\
Default font size must be at least 1 point (value of 1000 for key `%s').", 703},
  {"Value for `%s' must be a dimension of positive length (i.e., `1in').", 704},
  {"Nonnegative integer required as value for `%s'.", 705},
  {"%s: %s: Opening PostScript font encoding...", 706},
  {"\
PostScript driver: Cannot open encoding file `%s': %s.  Substituting \
ISOLatin1Encoding for missing encoding.", 707},
  {"PostScript driver: Invalid numeric format.", 708},
  {"\
PostScript driver: Codes must be between 0 and 255.  (%d is not allowed.)", 709},
  {"PostScript driver: Error closing encoding file `%s'.", 710},
  {"%s: PostScript font encoding read successfully.", 711},
  {"%s: %s: Opening PostScript encoding list file.", 712},
  {"%s: PostScript encoding list file read successfully.", 713},
  {"<<default encoding>>", 714},
  {"\
Cannot find PostScript prologue.  The use of `-vv' on the command line is \
suggested as a debugging aid.", 715},
  {"%s: %s: Opening PostScript prologue...", 716},
  {"%s: PostScript prologue read successfully.", 717},
  {"%s: Error reading PostScript prologue.", 718},
  {"PostScript output driver: %s: %s", 719},
  {"PostScript driver: Cannot find encoding `%s' for PostScript font `%s'.", 720},
  {"bad vline: x=%d+%d=%d y=(%d+%d=%d,%d+%d=%d) in table size (%d,%d)\n", 721},
  {"bad hline: x=(%d+%d=%d,%d+%d=%d) y=%d+%d=%d in table size (%d,%d)\n", 722},
  {"\
bad box: (%d+%d=%d,%d+%d=%d)-(%d+%d=%d,%d+%d=%d) in table size (%d,%d)\n", 723},
  {"There is no DO IF to match with this ELSE IF.", 724},
  {"The ELSE command must follow all ELSE IF commands in a DO IF structure.", 725},
  {"End of command expected.", 726},
  {"There is no DO IF to match with this ELSE.", 727},
  {"\
There may be at most one ELSE clause in each DO IF structure.  It must be \
the last clause.", 728},
  {"There is no DO IF to match with this END IF.", 729},
  {"DO IF %d: true\n", 730},
  {"DO IF %d: false\n", 731},
  {"DO IF %d: missing\n", 732},
  {"\
Missing mode REPORT not allowed in general mode.  Assuming MISSING=TABLE.", 733},
  {"Write mode ALL not allowed in general mode.  Assuming WRITE=CELLS.", 734},
  {"expecting BY", 735},
  {"VARIABLES must be specified before TABLES.", 736},
  {"Maximum value (%ld) less than minimum value (%ld).", 737},
  {"Summary.", 738},
  {"Cases", 739},
  {"Valid", 740},
  {"Missing", 741},
  {"Total", 742},
  {"N", 743},
  {"Percent", 744},
  {"count", 745},
  {"row %", 746},
  {"column %", 747},
  {"total %", 748},
  {"expected", 749},
  {"residual", 750},
  {"std. resid.", 751},
  {"adj. resid.", 752},
  {"Statistic", 753},
  {"df", 754},
  {"Asymp. Sig. (2-sided)", 755},
  {"Exact. Sig. (2-sided)", 756},
  {"Exact. Sig. (1-sided)", 757},
  {"Category", 758},
  {"Asymp. Std. Error", 759},
  {"Approx. T", 760},
  {"Approx. Sig.", 761},
  {" 95%% Confidence Interval", 762},
  {"Lower", 763},
  {"Upper", 764},
  {"Type", 765},
  {"Pearson Chi-Square", 766},
  {"Likelihood Ratio", 767},
  {"Fisher's Exact Test", 768},
  {"Continuity Correction", 769},
  {"Linear-by-Linear Association", 770},
  {"N of Valid Cases", 771},
  {"Nominal by Nominal", 772},
  {"Ordinal by Ordinal", 773},
  {"Interval by Interval", 774},
  {"Measure of Agreement", 775},
  {"Phi", 776},
  {"Cramer's V", 777},
  {"Contingency Coefficient", 778},
  {"Kendall's tau-b", 779},
  {"Kendall's tau-c", 780},
  {"Gamma", 781},
  {"Spearman Correlation", 782},
  {"Pearson's R", 783},
  {"Kappa", 784},
  {"Odds Ratio for %s (%g / %g)", 785},
  {"Odds Ratio for %s (%.*s / %.*s)", 786},
  {"For cohort %s = %g", 787},
  {"For cohort %s = %.*s", 788},
  {"Nominal by Interval", 789},
  {"Lambda", 790},
  {"Goodman and Kruskal tau", 791},
  {"Uncertainty Coefficient", 792},
  {"Somers' d", 793},
  {"Eta", 794},
  {"Symmetric", 795},
  {"%s Dependent", 796},
  {"Mean", 797},
  {"mean", 798},
  {"S.E. Mean", 799},
  {"S E Mean", 800},
  {"SE", 801},
  {"standard error of mean", 802},
  {"Std Dev", 803},
  {"SD", 804},
  {"standard deviation", 805},
  {"Variance", 806},
  {"Var", 807},
  {"variance", 808},
  {"Kurtosis", 809},
  {"Kurt", 810},
  {"kurtosis", 811},
  {"S.E. Kurt", 812},
  {"S E Kurt", 813},
  {"SEKurt", 814},
  {"standard error of kurtosis", 815},
  {"Skewness", 816},
  {"Skew", 817},
  {"skewness", 818},
  {"S.E. Skew", 819},
  {"S E Skew", 820},
  {"SESkew", 821},
  {"standard error of skewness", 822},
  {"Range", 823},
  {"Rng", 824},
  {"Minimum", 825},
  {"Min", 826},
  {"minimum", 827},
  {"Maximum", 828},
  {"Max", 829},
  {"maximum", 830},
  {"Sum", 831},
  {"sum", 832},
  {"No variables specified.", 833},
  {"OPTIONS may not be used with SAVE, FORMAT, or MISSING.", 834},
  {"It's not possible to sort on `%s' without displaying `%s'.", 835},
  {"\
At least one case in the data file had a weight value that was \
system-missing, zero, or negative.  These case(s) were ignored.", 836},
  {"\
Names for z-score variables must be given for individual variables, not for \
groups of variables.", 837},
  {"Name for z-score variable expected.", 838},
  {"\
Z-score variable name `%s' is a duplicate variable name with a current \
variable.", 839},
  {"Z-score variable name `%s' is used multiple times.", 840},
  {"`)' expected after z-score variable name.", 841},
  {"\
Ran out of generic names for Z-score variables.  There are only 126 generic \
names: ZSC001-ZSC0999, STDZ01-STDZ09, ZZZZ01-ZZZZ09, ZQZQ01-ZQZQ09.", 842},
  {"Mapping of variables to corresponding Z-scores.", 843},
  {"Source", 844},
  {"Target", 845},
  {"Z-score of ", 846},
  {"Valid N", 847},
  {"Missing N", 848},
  {"Valid cases = %g; cases with missing value(s) = %g.", 849},
  {"Median", 850},
  {"Mode", 851},
  {"\
At most one of BARCHART, HISTOGRAM, or HBAR should be given.  HBAR will be \
assumed.  Argument values will be given precedence increasing along the \
order given.", 852},
  {"\
MAX must be greater than or equal to MIN, if both are specified.  However, \
MIN was specified as %g and MAX as %g.  MIN and MAX will be ignored.", 853},
  {"\
Upper limit of integer mode value range must be greater than lower limit.", 854},
  {"Variable %s specified multiple times on VARIABLES subcommand.", 855},
  {"Integer mode specified, but %s is not a numeric variable.", 856},
  {"`)' expected after GROUPED interval list.", 857},
  {"Variables %s specified on GROUPED but not on VARIABLES.", 858},
  {"Variables %s specified multiple times on GROUPED subcommand.", 859},
  {"Percentile list expected after PERCENTILES.", 860},
  {"Percentiles must be greater than 0 and less than 100.", 861},
  {"Cum", 862},
  {"Frequency", 863},
  {"Value Label", 864},
  {"Freq", 865},
  {"Pct", 866},
  {"No valid data for variable %s; statistics not displayed.", 867},
  {"only %g case%s for variable %s, statistics not computed", 868},
  {"\
The variable %s has %d modes.  The lowest of these is the one given in the \
table.", 869},
  {"Percentage", 870},
  {"low-res graphs not implemented", 871},
  {"\
Could not make histogram for %s for specified minimum %g and maximum %g; \
please discard graph.", 872},
  {"Percentile    Value     Percentile    Value     Percentile    Value", 873},
  {"this form of percentiles not supported", 874},
  {"Difference between %g and %g is too small for grouping interval %g.", 875},
  {"\
The first case (%ld) specified precedes the last case (%ld) specified.  The \
values will be swapped.", 876},
  {"\
The first case (%ld) to list is less than 1.  The value is being reset to 1.", 877},
  {"\
The last case (%ld) to list is less than 1.  The value is being reset to 1.", 878},
  {"The step value %ld is less than 1.  The value is being reset to 1.", 879},
  {"`/FORMAT WEIGHT' specified, but weighting is not on.", 880},
  {"Line", 881},
  {"Missing required subcommand TABLES.", 882},
  {"TABLES or CROSSBREAK subcommand may not appear more than once.", 883},
  {"\
Variable %s specified on TABLES or CROSSBREAK, but not specified on \
VARIABLES.", 884},
  {"LOWEST and HIGHEST may not be used for independent variables (%s).", 885},
  {"\
Independent variables (%s) may not have noninteger endpoints in their ranges.", 886},
  {"Variable %s is multiply specified on TABLES or CROSSBREAK.", 887},
  {"VARIABLES must precede TABLES.", 888},
  {"Upper value (%g) is less than lower value (%g) on VARIABLES subcommand.", 889},
  {"expecting variable name in GROUPS subcommand", 890},
  {"Long string variable %s is not valid here.", 891},
  {"\
When applying GROUPS to a string variable, at least one value must be \
specified.", 892},
  {"\
PAIRED was specified but the number of variables preceding WITH (%d) did not \
match the number following (%d).", 893},
  {"At least two variables must be specified on PAIRS.", 894},
  {"Destination cannot be a string variable.", 895},
  {"\
%g THRU %g is not a valid range.  The number following THRU must be at least \
as big as the number preceding THRU.", 896},
  {"Vartree:\n", 897},
  {"clearing variable %d:%s %s\n", 898},
  {"in default dictionary", 899},
  {"in auxiliary dictionary", 900},
  {"%s is not declared as a variable.", 901},
  {"%s is not a variable name.", 902},
  {"%s TO %s is not valid syntax since %s precedes %s in the dictionary.", 903},
  {"\
When using the TO keyword to specify several variables, both variables must \
be from the same variable dictionaries, of either ordinary, scratch, or \
system variables.  %s and %s are from different dictionaries.", 904},
  {"Scratch variables (such as %s) are not allowed here.", 905},
  {"\
%s is not a numeric variable.  It will not be included in the variable list.", 906},
  {"\
%s is not a string variable.  It will not be included in the variable list.", 907},
  {"\
%s and %s are not the same type.  All variables in this variable list must \
be of the same type.  %s will be omitted from list.", 908},
  {"Variable %s appears twice in variable list.", 909},
  {"incorrect use of TO convention", 910},
  {"Scratch variables not allowed here.", 911},
  {"Prefixes don't match in use of TO convention.", 912},
  {"Bad bounds in use of TO convention.", 913},
  {"\
Workspace overflow predicted.  Max workspace is currently set to %d KB (%d \
cases at %d bytes each).  Paging active file to disk.", 914},
  {"!ERROR!", 915},
  {"<NOVAR>", 916},
  {"\
An error occurred attempting to create a temporary file for use as the \
active file: %s.", 917},
  {"\
An error occurred while attempting to read from a temporary file created for \
the active file: %s.", 918},
  {"\
An error occurred while attempting to write to a temporary file used as the \
active file: %s.", 919},
  {"\
An error occurred while attempting to rewind a temporary file used as the \
active file: %s.", 920},
  {"Virtual memory exhausted.  Paging active file to disk.", 921},
  {"\
Workspace limit of %d KB (%d cases at %d bytes each) overflowed.  Paging \
active file to disk.", 922},
  {"\
An error occurred while attempting to write to a temporary file created as \
the active file, while paging to disk: %s.", 923},
  {"transform: ", 924},
  {"Target variable %s duplicates existing variable %s.", 925},
  {"Duplicate variable name %s among target variables.", 926},
  {"\
When executing COMPUTE: SYSMIS is not a valid value as an index into vector \
%s.", 927},
  {"\
When executing COMPUTE: %g is not a valid value as an index into vector %s.", 928},
  {"There is no vector named %s.", 929},
  {"Extra characters after expression.", 930},
  {"Could not create acceptable variant for variable %s.", 931},
  {"Cannot create more than 99999 variable names.", 932},
  {"Error reading FLIP source file: %s.", 933},
  {"Could not create temporary file for FLIP.", 934},
  {"Error writing FLIP file: %s.", 935},
  {"Error creating FLIP source file.", 936},
  {"Error rewinding FLIP file: %s.", 937},
  {"Error reading FLIP file: %s.", 938},
  {"Error seeking FLIP source file: %s.", 939},
  {"Error writing FLIP source file: %s.", 940},
  {"Error rewind FLIP source file: %s.", 941},
  {"expecting a valid subcommand", 942},
  {"%g is not a valid column location.", 943},
  {"Column location expected following `%d-'.", 944},
  {"\
%d-%ld is not a valid column range.  The second column must be greater than \
or equal to the first.", 945},
  {"\
%s is not of the same type as %s.  To specify variables of different types \
in the same variable list, use a FORTRAN-like format specifier.", 946},
  {"\
The ending column for a field must not be less than the starting column.", 947},
  {"%s variables cannot be displayed with format %s.", 948},
  {"Display format %s may not be used with a %s variable.", 949},
  {"Writing %3d records to file %s.", 950},
  {"Writing %3d records to the listing file.", 951},
  {"A file name or handle was expected in the OUTFILE subcommand.", 952},
  {"\
The expression on PRINT SPACE evaluated to %d.  It's not possible to PRINT \
SPACE a negative number of lines.", 953},
  {"\
%d variable(s) cannot be recoded into %d variable(s).  Specify the same \
number of variables as input and output variables.", 954},
  {"\
There is no string variable named %s.  (All string variables specified on \
INTO must already exist.  Use the STRING command to create a string \
variable.)", 955},
  {"\
Type mismatch between input and output variables.  Output variable %s is not \
a string variable, but all the input variables are string variables.", 956},
  {"Type mismatch after INTO: %s is not a numeric variable.", 957},
  {"\
INTO must be used when the input values are numeric and output values are \
string.", 958},
  {"\
INTO must be used when the input values are string and output values are \
numeric.", 959},
  {"\
Inconsistent output types.  The output values must be all numeric or all \
string.", 960},
  {"following LO THRU", 961},
  {"in source value", 962},
  {"\
Keyword CONVERT may only be used with string input values and numeric output \
values.", 963},
  {"!!END!!", 964},
  {"!!ERROR!!", 965},
  {"The filter variable must be numeric.", 966},
  {"The filter variable may not be scratch.", 967},
  {"Only last instance of this command is in effect.", 968},
  {"`A' or `D' expected inside parentheses.", 969},
  {"`)' expected.", 970},
  {"%s: Cannot create temporary directory: %s.", 971},
  {"%s: Error removing directory for temporary files: %s.", 972},
  {"\
Out of memory.  Could not allocate room for minimum of %d cases of %d bytes \
each.  (PSPP workspace is currently restricted to a maximum of %d KB.)", 973},
  {"allocated %d cases == %d bytes\n", 974},
  {"%s: Error writing temporary file: %s.", 975},
  {"SORT: Closing handle %d.", 976},
  {"%s: Error closing temporary file: %s.", 977},
  {"SORT: %s: Opening for writing as run %d.", 978},
  {"%s: Error opening temporary file for reading: %s.", 979},
  {"%s: Error creating temporary file: %s.", 980},
  {"%s: Error removing temporary file: %s.", 981},
  {"merging runs", 982},
  {" into run %d(%d)\n", 983},
  {"Out of memory expanding Huffman priority queue.", 984},
  {"%s: Error creating temporary file for merge: %s.", 985},
  {"%s: Error reading temporary file in merge: %s.", 986},
  {"%s: Unexpected end of temporary file in merge.", 987},
  {"%s: Error writing temporary file in merge: %s.", 988},
  {"%s: Error closing temporary file in merge: %s.", 989},
  {"%s: Error removing temporary file in merge: %s.", 990},
  {"%s: Cannot open sort result file: %s.", 991},
  {"%s: Error reading sort result file: %s.", 992},
  {"%s: Unexpected end of sort result file: %s.", 993},
  {"%s: Error closing sort result file: %s.", 994},
  {"%s: Error removing sort result file: %s.", 995},
  {"Unrecognized filename format.", 996},
  {"The index variable may not be a string variable.", 997},
  {"There is no LOOP command that corresponds to this END LOOP.", 998},
  {"\
This command may only appear enclosed in a LOOP/END LOOP control structure.", 999},
  {"BREAK not enclosed in DO IF structure.", 1000},
  {"%s without %s.", 1001},
  {"Identifier %s is given twice.", 1002},
  {"\
There must be the same number of substitutions for each dummy variable \
specified.  Since there were %d substitutions for %s, there must be %d for \
%s as well, but %d were specified.", 1003},
  {"No commands in scope.", 1004},
  {"String expected.", 1005},
  {"No matching DO REPEAT.", 1006},
  {"`)' expected after value specification.", 1007},
  {"`(' expected after variable name%s.", 1008},
  {"Long string value specified.", 1009},
  {"Short strings must be of equal width.", 1010},
  {"Range %g THRU %g is not valid because %g is greater than %g.", 1011},
  {"Number or range expected.", 1012},
  {"At most one range can exist in the missing values for any one variable.", 1013},
  {"At most one individual value can be missing along with one range.", 1014},
  {"String is not of proper length.", 1015},
  {"Missing value:", 1016},
  {"(long string variable)", 1017},
  {"(no missing values)\n", 1018},
  {"(!!!INTERNAL ERROR--%d!!!)\n", 1019},
  {"REORDER subcommand may be given at most once.", 1020},
  {"Cannot specify ALL after specifying a set of variables.", 1021},
  {"`(' expected on REORDER subcommand.", 1022},
  {"`)' expected following variable names on REORDER subcommand.", 1023},
  {"RENAME subcommand may be given at most once.", 1024},
  {"`(' expected on RENAME subcommand.", 1025},
  {"\
`=' expected between lists of new and old variable names on RENAME \
subcommand.", 1026},
  {"\
Differing number of variables in old name list (%d) and in new name list \
(%d).", 1027},
  {"`)' expected after variable lists on RENAME subcommand.", 1028},
  {"\
KEEP subcommand may be given at most once.  It may notbe given in \
conjunction with the DROP subcommand.", 1029},
  {"\
DROP subcommand may be given at most once.  It may notbe given in \
conjunction with the KEEP subcommand.", 1030},
  {"Unrecognized subcommand name `%s'.", 1031},
  {"Subcommand name expected.", 1032},
  {"`/' or `.' expected.", 1033},
  {"Duplicate variable name `%s' after renaming.", 1034},
  {"Format type %s may not be used with a numeric variable.", 1035},
  {"There is already a variable named %s.", 1036},
  {"Format type %s may not be used with a string variable.", 1037},
  {"`(' expected.", 1038},
  {"`=' expected between lists of new and old variable names.", 1039},
  {"`)' expected after variable names.", 1040},
  {"The sampling factor must be between 0 and 1 exclusive.", 1041},
  {"Cannot sample %d observations from a population of %d.", 1042},
  {"BLOCK is obsolete.", 1043},
  {"BOXSTRING is obsolete.", 1044},
  {"Active file compression is not yet implemented (and probably won't be).", 1045},
  {"CPI must be greater than 0.", 1046},
  {"HISTOGRAM is obsolete.", 1047},
  {"LPI must be greater than 0.", 1048},
  {"\
CASE is not implemented and probably won't be.  If you care, complain about \
it.", 1049},
  {"Value for MITERATE (%ld) must be greater than 0.", 1050},
  {"Value for MNEST (%ld) must be greater than 0.", 1051},
  {"MXERRS must be at least 1.", 1052},
  {"MXLOOPS must be at least 1.", 1053},
  {"MXMEMORY is obsolete.", 1054},
  {"SCRIPTTAB is obsolete.", 1055},
  {"TBFONTS not implemented.", 1056},
  {"TB1 not implemented.", 1057},
  {"WORKSPACE is obsolete.", 1058},
  {"AUTOMENU is obsolete.", 1059},
  {"BEEP is obsolete.", 1060},
  {"EJECT is obsolete.", 1061},
  {"HELPWINDOWS is obsolete.", 1062},
  {"MENUS is obsolete.", 1063},
  {"PTRANSLATE is obsolete.", 1064},
  {"XSORT is obsolete.", 1065},
  {"\
CC%c: Length of custom currency string `%s' (%d) exceeds maximum length of \
16.", 1066},
  {"\
CC%c: Custom currency string `%s' does not contain exactly three periods or \
commas (not both).", 1067},
  {"LENGTH must be at least 1.", 1068},
  {"Missing identifier in RESULTS subcommand.", 1069},
  {"Unrecognized identifier in RESULTS subcommand.", 1070},
  {"WIDTH must be at least 1.", 1071},
  {"\
FORMAT requires numeric output format as an argument.  Specified format %s \
is of type string.", 1072},
  {"Text color must be in range 0-15.", 1073},
  {"Background color must be in range 0-7.", 1074},
  {"Border color must be in range 0-7.", 1075},
  {"RCOLOR is obsolete.", 1076},
  {"Lower window color must be between 0 and 6.", 1077},
  {"Upper window color must be between 0 and 6.", 1078},
  {"Frame color must be between 0 and 6.", 1079},
  {"VIEWLENGTH not implemented.", 1080},
  {"WORKDEV is obsolete.", 1081},
  {"Drive letter expected in WORKDEV subcommand.", 1082},
  {"This command is not valid inside DO IF or LOOP.", 1083},
  {"\
This command may only appear once between procedures and procedure-like \
commands.", 1084},
  {"%s before: %s\n", 1085},
  {"<none>", 1086},
  {"%s: `.' expected after string.", 1087},
  {"%s after: %s\n", 1088},
  {"Document entered %s %02d:%02d:%02d by %s (%s):", 1089},
  {"\
It is not possible to assign value labels to long string variables such as \
%s.", 1090},
  {"String expected for value.", 1091},
  {"Number expected for value.", 1092},
  {"Value label `%g' is not integer.", 1093},
  {"Truncating value label to 60 characters.", 1094},
  {"Value labels:", 1095},
  {"    (no value labels)\n", 1096},
  {"String expected for variable label.", 1097},
  {"Truncating variable label to 120 characters.", 1098},
  {"Variable labels:\n", 1099},
  {"(no variable label)", 1100},
  {"Vector name %s is given twice.", 1101},
  {"There is already a vector with name %s.", 1102},
  {"\
A slash must be used to separate each vector specification when using the \
long form.  Commands such as VECTOR A,B=Q1 TO Q20 are not supported.", 1103},
  {"Vectors must have at least one element.", 1104},
  {"%s%d is too long for a variable name.", 1105},
  {"\
The syntax for this command does not match the expected syntax for either \
the long form or the short form of VECTOR.", 1106},
  {"The weighting variable must be numeric.", 1107},
  {"The weighting variable may not be scratch.", 1108},
  {"bad weighting variable, canceling\n", 1109},
};

int _msg_tbl_length = 1109;
