/* PSPP - Comments for C files generated by REGRESSION's EXPORT subcommand.
   Copyright (C) 2005 Free Software Foundation, Inc.
   Written by Jason H Stover <jason@sakla.net>.

   This program is free software; you can redistribute it and/or
   modify it under the terms of the GNU General Public License as
   published by the Free Software Foundation; either version 2 of the
   License, or (at your option) any later version.

   This program is distributed in the hope that it will be useful, but
   WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
   02110-1301, USA. */

#ifndef REG_EXPORT_COMMENTS_H
#define REG_EXPORT_COMMENTS_H
const char reg_preamble[] =  "/*\n   This program contains functions which return estimates\n"
"   and confidence intervals for a linear model. The EXPORT subcommand\n"
"   of the REGRESSION procedure of GNU PSPP generated this program.\n*/\n\n";
const char reg_mean_cmt[] =  "/*\n   Estimate the mean of Y, the dependent variable for\n"
"   the linear model of the form \n\n"
"      Y = b0 + b1 * X1 + b2 * X2 + ... + bk * Xk + error\n\n"
"   where X1, ..., Xk are the independent variables\n"
"   whose values are stored in var_vals and whose names, \n"
"   as known by PSPP, are stored in var_names. The estimated \n"
"   regression coefficients (i.e., the estimates of b0,...,bk) \n"
"   are stored in model_coeffs.\n*/\n";
#endif
